// Code generated by "stringer -type=BoxMode"; DO NOT EDIT

package cmd

import "fmt"

const _BoxMode_name = "ModeServeModeRefineModeInit"

var _BoxMode_index = [...]uint8{0, 9, 19, 27}

func (i BoxMode) String() string {
	if i < 0 || i >= BoxMode(len(_BoxMode_index)-1) {
		return fmt.Sprintf("BoxMode(%d)", i)
	}
	return _BoxMode_name[_BoxMode_index[i]:_BoxMode_index[i+1]]
}
