// Code generated by "stringer -type=ProxyType"; DO NOT EDIT

package proxy

import "fmt"

const _ProxyType_name = "UndefinedProxyCaddyNginx"

var _ProxyType_index = [...]uint8{0, 14, 19, 24}

func (i ProxyType) String() string {
	if i < 0 || i >= ProxyType(len(_ProxyType_index)-1) {
		return fmt.Sprintf("ProxyType(%d)", i)
	}
	return _ProxyType_name[_ProxyType_index[i]:_ProxyType_index[i+1]]
}
